version: '3'
services:
  ci:
    image: golang
    working_dir: "/srv/app"
    volumes:
    - .:/srv/app
    environment:
        MYSQL_USER: travis
        MYSQL_PASSWORD: travis
        MYSQL_DATABASE: gossip_test
        PORT: 7483
        GOSSIP_DB_URL: travis:travis@tcp(mysql)/gossip
        GOSSIP_DB_HOSTNAME: tcp(mysql)
        GOSSIP_DB_USERNAME: travis
        GOSSIP_DB_PASSWORD: travis
        GOSSIP_DB_DBNAME: gossip_test
        GOSSIP_AUTH_TOKEN: blah
  mysql:
    image: "mysql:5.7"
    environment:
        MYSQL_USER: travis
        MYSQL_PASSWORD: travis
        MYSQL_DATABASE: gossip_test
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"