version: '3'
services:
  ci:
    image: golang
    working_dir: "/srv/app"
    volumes:
    - .:/srv/app
    environment:
        PORT: 7483
        GOSSIP_DB_PATH: ./data/gossip_test.sqlite3
        GOSSIP_AUTH_TOKEN: blah
